import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [Frame()])),
    );
  }
}

class Frame extends StatelessWidget {
  const Frame({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1440,
          height: 810,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 1440,
                  height: 810,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 1440,
                  height: 810,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 2032.90,
                top: 1527.81,
                child: Container(
                  transform:
                      Matrix4.identity()
                        ..translate(0.0, 0.0)
                        ..rotateZ(-2.42),
                  width: 1326.75,
                  height: 264,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/1327x264"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 86,
                top: 536.90,
                child: Container(
                  width: 341,
                  height: 73,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 360,
                top: 543,
                child: Container(
                  width: 60.90,
                  height: 60.80,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 1440,
                  height: 810,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 111,
                        top: 555,
                        child: SizedBox(
                          width: 92.51,
                          height: 34.99,
                          child: Text(
                            'Login',
                            style: TextStyle(
                              color: const Color(0xFF13072E),
                              fontSize: 34.90,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w400,
                              height: 1,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 364.30,
                top: 552.60,
                child: Container(
                  width: 52.50,
                  height: 41.30,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 1160.70,
                top: 55.30,
                child: Container(
                  width: 241.60,
                  height: 65.20,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 1440,
                  height: 810,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 86.04,
                        top: 324.87,
                        child: SizedBox(
                          width: 780.25,
                          height: 174.58,
                          child: Text(
                            'TO MONITOR\nYOUR ENERGY',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 80.90,
                              fontFamily: 'League Spartan',
                              fontWeight: FontWeight.w700,
                              height: 1.16,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 86.04,
                        top: 265.47,
                        child: SizedBox(
                          width: 273.25,
                          height: 37.64,
                          child: Text(
                            'SmartWatts',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 37.60,
                              fontFamily: 'Montserrat',
                              fontWeight: FontWeight.w700,
                              height: 1,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 1242.50,
                top: 55.30,
                child: Container(
                  width: 135.90,
                  height: 57.40,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 1440,
                  height: 810,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 1263.27,
                        top: 66.04,
                        child: SizedBox(
                          width: 94.51,
                          height: 25,
                          child: Text(
                            'Sign Up',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 24.90,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w400,
                              height: 1,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 496,
                        top: 170,
                        child: Container(
                          width: 1138,
                          height: 640,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage(
                                "https://placehold.co/1138x640",
                              ),
                              fit: BoxFit.cover,
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(122),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
